### ISSUE TITLE
minQuestionSize problem in padding

### ISSUE THREAD

**Issue by zoli** [ameshkov/dnscrypt#24]
From what I understand [this](https://github.com/ameshkov/dnscrypt/blob/master/util.go#L45) line in `pad` function isn't right.
```go
// get closest divisible by 64 to <packet-len> + 1 byte for 0x80
minQuestionSize := (len(packet)+1+63)/64 + 64
```
It doesn't result in closes divisible by 64. For example if `packet` length is 56 it will result in 65 which should be 64 (the closest divisible by 64 to 56+1 is 64).
I think it should get rewritten to STH like this:
```go
minQuestionSize := len(packet) + 1 + (64 - (len(packet)+1)%64)
```

**Comment by ameshkov** [comment]
Would you like to submit a pull request? If you do, please also add a unit-test for this case.

**Comment by alsalf001401-star** [comment]
Hu
