### ISSUE TITLE
You should update your document.

### ISSUE THREAD

**Issue by iamsurfing** [ameshkov/dnscrypt#8]
`resolverInfo, err := client.Dial(stampStr`
`reply, err := c.Exchange(&req, resolverInfo))`

Now it is 3 args.

**Comment by ameshkov** [comment]
Why, it's two args: https://github.com/ameshkov/dnscrypt/blob/master/client.go#L82

**Comment by iamsurfing** [comment]
func (c *Client) Exchange(m *dns.Msg, s *ServerInfo) (*dns.Msg, time.Duration, error)
func (c *Client) Dial(stampStr string) (*ServerInfo, time.Duration, error)

github.com/ameshkov/dnscrypt@v1.1.0

I do not know why, but IDE ask me.

**Comment by ameshkov** [comment]
You're using the old version, use `github.com/ameshkov/dnscrypt/v2`

**Comment by iamsurfing** [comment]
Thanks, but I think you can write it to sample code. #9

**Comment by ameshkov** [comment]
Makes sense, thank you!
